# Generated by Django 4.2.6 on 2024-04-10 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0018_auto_20201015_2036"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="remarks",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
