# Generated by Django 4.2.6 on 2024-04-20 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0025_alter_remarks_assigneddoctorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Medical Oncologists', 'Medical Oncologists'), ('Surgical Oncologists', 'Surgical Oncologists'), ('Radiation Oncologists', 'Radiation Oncologists'), ('Hematologists/Oncologists', 'Hematologists/Oncologists'), ('Pediatric Oncologists', 'Pediatric Oncologists'), ('Gynecologic Oncologists', 'Gynecologic Oncologists')], default='Cardiologist', max_length=50),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.URLField(null=True)),
                ('video', models.URLField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
